version: '3'

services:
    FamilyBudget:
        image: postgres:latest
        container_name: FamilyBudgetDB
        hostname: FamilyBudget
        restart: unless-stopped
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"
        volumes:
            - ./.container/postgres:/var/lib/postgresql
            - ./.container/postgres:/var/log/postgresql
        command: -p 5432
